#!/bin/sh
set -e
set -u
n=0
max=2
until [ $n -gt $max ]; do
    set +e
    (
      microdnf update -y && \
      microdnf install -y --nodocs "$@"
    )
    CODE=$?
    set -e
    if [ $CODE -eq 0 ]; then
        break
    fi
    if [ $n -eq $max ]; then
        exit $CODE
    fi
    echo "microdnf failed, retrying"
    n=$(($n + 1))
done
microdnf clean all
